### ISSUE TITLE
Error after compiling

### ISSUE THREAD

**Issue by keivy-git** [CubeIsland/AntiGuest#40]
Hi 

After compiling, I have this error : 
```
[11:23:00] [Server thread/ERROR]: Could not load 'plugins\AntiGuest.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: de/cubeisland/libMinecraft/translation/TranslatablePlugin
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NoClassDefFoundError: de/cubeisland/libMinecraft/translation/TranslatablePlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	... 7 more
Caused by: java.lang.ClassNotFoundException: de.cubeisland.libMinecraft.translation.TranslatablePlugin
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	... 7 more
```

A solution ?

Thanks

**Comment by pschichtel** [comment]
Seems like you didn't shade the dependencies

**Comment by keivy-git** [comment]
I compiling with maven^^"

plugin => jar => jar:jar

**Comment by pschichtel** [comment]
You should just run the package phase, that builds the jar and shades the dependencies. Since I configured the default goal, just running `mvn` should already be enough.

I also did a few changes on master, so it actually compiles.

**Comment by keivy-git** [comment]
Hi, error log

https://pastebin.com/srh4aCiF

Thanks you...

**Comment by pschichtel** [comment]
Please fetch the latest changes. The fix for that is part of the changes I mentioned in the last comment.

**Comment by keivy-git** [comment]
Ok perfect :) 

Good days
